name: Live Demo pipeline

on:
  push:
    branches:
      - live-demo

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      # - name: Lint Code
      #   run: npm run lint
  
  security:
      runs-on: ubuntu-latest
      needs:
        - lint
      steps:
        - uses: actions/checkout@v3
        - name: Install Dependencies
          run: npm install
        - name: Check for Vulnerabilities
          run: npm audit fix --force

  
  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}:typescript-app:test .

        
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:   
      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/typescript-app:test
